server:
  port: 9000


spring:
  config:
    import:
      - "application_prd.yml"
      - "application_val.yml"
  profiles:
    active:
    - "prd"

  application:
    name: MicroServiceAccounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

build:
  version: "3.0"

cards:
  message: "Welcome to cards Microservice - Developer Console"
  ContactDetails:
    Developer: "Shivam Sharma"
    email: "sharmaascent6@gmail.com"
  onCallSupport:
    - 9958093592
    - 9811708082

